
image: docker:23.0

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

services:
  - name: docker:23.0-dind
    alias: docker

variables:
  GITLAB_RUNNER_TAG: "shared"

stages:
  - build
  - scanning

# =============================================================================

build_tagged:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG =~ /^(\d+\.)?(\d+\.)?(\*|\d+)(\+.*?)?$/

  tags:
    - docker
    - "${GITLAB_RUNNER_TAG}"

  before_script:
    - export BUILD_TAG="$(echo ${CI_COMMIT_TAG} | tr '+' '-')"
    - export BUILD1_NAME="${CI_REGISTRY_IMAGE}"

  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --password-stdin -u "${CI_REGISTRY_USER}" "${CI_REGISTRY}"
    - docker build --pull --tag "${BUILD1_NAME}:${BUILD_TAG}" --tag "${BUILD1_NAME}:latest" --build-arg COMMIT_TAG=${CI_COMMIT_TAG} .
    - docker push "${BUILD1_NAME}:${BUILD_TAG}"
    - docker push "${BUILD1_NAME}:latest"
    - docker logout

# =============================================================================

container_scanning:
  stage: scanning
  tags:
    - "${GITLAB_RUNNER_TAG}"
  variables:
    CS_IMAGE: $CI_REGISTRY_IMAGE:latest
